using System.Collections.Generic;

namespace LastLight
{
    public static class M3Narrative
    {
        public static readonly Dictionary<string,string> Records=new Dictionary<string,string>{
            {"wake-ya",M3Text.Pair("芽的托盘先动了一下，随后才亮起指示灯。它没有询问今天的产量，而是把一盆干枯的植物挪到光下。\n\n“这是最后一盆没有用途的植物。”它说，“记录上写着，不结果，不供油，也不能做纤维。我想先确认：恢复工作之后，它还能留在这里吗？”\n\n你告诉它，家园有地方。芽展开叶形遮罩，露出下面修补过三次的温度计。它可以照料种植箱，也可以去安全地带收集普通物资，但一次只能做一件事。把岗位写清楚，意味着照料终于不必等于永远工作。", "Ya's tray moves before its indicator lights. Instead of asking for today's yield, it shifts a dried plant into the light.\n\n'This is the last plant without a use,' it says. 'The record says it bears no food, oil or fibre. Before work resumes, may it stay?'\n\nYou tell it there is room at home. Ya unfolds its leaf-shaped hood, revealing a thermometer repaired three times. It can tend planters or gather ordinary supplies nearby, but only one job at a time. Writing down that limit means care no longer has to mean endless work.")},
            {"insulation",M3Text.Pair("温室后墙的保温层里夹着一张旧标签：生物维护室，不对外开放。编号与维护舱里的编号相同。你把样本收进任务栏，它不会混进普通材料，也不会在倒下时遗失。\n\n绝缘层能够修复山路上暴露的线路。芽提醒你，路修好之后不必等夏天才出发，也不必先找到中继站里的守。入口的手摇应急装置曾经就是给独自抵达的人准备的。", "A label lies inside the greenhouse insulation: biological maintenance room, restricted access. Its serial matches the one in your waking pod. You secure the sample with your key items, beyond ordinary crafting or rescue losses.\n\nThe insulation can protect the exposed mountain cable. Ya points out that you need not wait for summer, or find Shou at the relay first. The entrance hand-powered emergency unit was built for someone arriving alone.")},
            {"relay-road",M3Text.Pair("断开的线缆接上了。风从桥下穿过，绝缘套没有再发出危险的噼啪声。你在路牌上补了一笔：中继站，可步行抵达。\n\n梁认真量了两遍扶手之间的距离。“足够一个人背着工具通过，也足够两个人错身。以前的要求只写了载荷，没有写第二个人。”\n\n这条通路不属于某一位伙伴。即使机器停机，你也能沿着主路到达应急供电装置；支路上的残件可以以后再来取。", "The cable reconnects. Wind passes under the crossing, and the insulating sleeve no longer spits sparks. You amend the sign: Relay station, accessible on foot.\n\nLiang measures the gap between the rails twice. 'Room for one person carrying tools, and room for two to pass. The old specification listed load capacity. It never mentioned a second person.'\n\nThe route belongs to no single companion. Even if the machines stop, you can reach emergency power on the main path. Salvage on the branch can wait.")},
            {"emergency-power",M3Text.Pair("你拉下手动启动柄，燃料点燃小型发电机。它只够维持入口、救援和检修设备，不能让整座中继站回到从前。\n\n控制台仍然接受“人类授权者”的身份。屏幕下方却多出一行校验信息：授权介质为生物组织，签发机构为地面维护联合体。\n\n守的单目灯在黑暗中亮了半圈。它的修复清单只有普通维修零件和这里的固定启动件，不要求一颗尚未解锁的电芯。", "You pull the manual starter and fuel catches in the small generator. It can support the entrance, rescue and maintenance equipment, not restore the entire station.\n\nThe console still accepts 'human authorizer'. Beneath it appears a new check: authorization medium, biological tissue; issuing body, Ground Maintenance Collective.\n\nHalf of Shou's single lamp glows in the dark. Its repair list requires ordinary parts and the fixed starter here, not an energy cell you have yet to unlock.")},
            {"wake-shou",M3Text.Pair("“威胁未知。权限有效。请求确认指挥关系。”守的第一句话像三行表格。\n\n你没有立刻回答。它等了一会儿，把灯光从你的脸上移开，照向脚边断裂的台阶。“在你确认之前，我可以先提醒这一级台阶。提醒不需要所有权。”\n\n守能够维护家园能源，降低运行消耗，也能巡查并提前预警。它还没有学会区分安全与服从，但它已经提出了第一个例外。", "'Threat unknown. Authorization valid. Confirm command relationship.' Shou's first words sound like three rows in a form.\n\nYou do not answer immediately. After waiting, it moves its light from your face to a broken step. 'Before confirmation, I can warn you about this step. A warning does not require ownership.'\n\nShou can maintain home energy to reduce consumption, or patrol to give earlier warnings. It has not yet learned to separate safety from obedience. It has already proposed its first exception.")},
            {"structure-plan",M3Text.Pair("图纸上既有单人航天器，也有一艘旧运输船。它们连接着同一套发射结构与导航设备。最下方有人用不同颜色写道：共同修复不等于共同出发。\n\n你把结构资料收好。它是一项永久掌握的能力，不能当普通材料交出去，也不会被某条准备路线独占。回到家园后，工程控制台会列出需要的普通材料与尚未取得的记录。", "The drawings show a personal craft and an old transport. Both use the same launch structure and navigation equipment. A note in a different colour reads: repairing together does not mean departing together.\n\nYou secure the plans. They represent a permanent capability, not material to trade away or consume on one route. The home console will list ordinary materials and records still needed.")},
            {"navigation-record",M3Text.Pair("导航记录的终点并不是一颗保证有人居住的星球，而是一串最后收到信号的坐标。人类离开后，这里的机器仍按时校准天线，直到没有足够的零件。\n\n最后一条人工批注说：如果后来者决定出发，请告诉他们，我们不知道对岸是否还有灯。未知不是禁止出发的理由，也不是可以隐瞒的成本。\n\n你保存了导航记录。寻找人类从此是一项明确的选择，而不再是一张保证兑现的返乡车票。", "The navigation archive ends with coordinates of the last signals received, not a world guaranteed to be inhabited. After humanity left, the machines kept calibrating the antenna until parts ran out.\n\nThe final annotation says: if someone later chooses to leave, tell them we do not know whether lights remain on the other side. Uncertainty is neither a ban on departure nor a cost to conceal.\n\nYou preserve the archive. Finding humanity is now an explicit choice, no longer a guaranteed ticket home.")},
            {"maker-record",M3Text.Pair("制造记录与温室的生物维护记录相互吻合：你不是被遗忘的撤离乘员。维护机器共同培育了你的身体，为它保留了饥饿、疼痛、适应冷热的能力，也赋予了旧系统能够识别的授权身份。\n\n记录没有写“必须服从”。它写的是：希望这个生命能够重新建立协作，并拥有拒绝我们的权利。\n\n守读到这里，关掉了身份扫描。芽问你要不要先吃点东西。真相没有取消饥饿，也没有使刚才递来的口粮变得虚假。", "The maker archive matches the greenhouse's biological records. You were not an abandoned evacuation passenger. Maintenance machines grew your body together, preserving hunger, pain and adaptation to heat and cold. They gave it an identity the old systems could recognize.\n\nThe record does not say 'must obey'. It says: we hope this life can rebuild cooperation and retain the right to refuse us.\n\nShou switches off its identity scan. Ya asks whether you would like something to eat. The truth has not abolished hunger, nor made the offered food unreal.")},
            {"structure",M3Text.Pair("支架从倾斜的废墟重新成为能承担重量的结构。梁放下工具，没有询问下一条命令。它先绕着基座走了一圈，确认这次维修没有把检修通道封死。\n\n你最初只是想造一条离开的路。如今，这条路由公共仓储、修好的桥、每天的口粮和许多次留下通道的决定组成。发射设施已经修复，接下来是共用动力。", "The leaning ruin becomes a structure able to bear weight again. Liang puts down its tools without asking for another order. It circles the base first, checking that the repair has not sealed the maintenance path.\n\nYou originally wanted only a road away. Now that road is made of public stores, a repaired bridge, daily meals and many decisions to leave room for passage. The launch structure is restored. Shared power comes next.")},
            {"power",M3Text.Pair("共用动力第一次稳定运转。它可以推动个人航天器，也可以支持旧运输船；如果留下，它同样能够为地面公共网络服务。\n\n守把三种用途并排写在控制台上，没有替其中任何一种加上优先标记。“容量是技术问题。谁能决定用途，是规则问题。”\n\n唯一核心的修复已永久记录。你不需要为了尝试另一条未来，把它重新拆下来。", "Shared power runs steadily for the first time. It can support the personal craft or the old transport. If you stay, it can serve a public network on the ground.\n\nShou lists the three uses side by side, assigning none priority. 'Capacity is a technical question. Who may decide its use is a question of rules.'\n\nRepair of the unique core is permanently recorded. Exploring another future will not require tearing it out again.")},
            {"navigation",M3Text.Pair("结构、动力与导航全部连通。控制台没有出现唯一的“正确路线”，而是并排显示留灯、远航和同行。每条道路都列出尚缺的设施、补给与答复。\n\n你可以准备不止一条路线，直到最后确认才冻结名单和消耗终局补给。没有人应该因为很久以前一句尚不知后果的话，被永久排除在未来之外。\n\n第四章开始了。下一步不是继续盲目囤积，而是问清楚：谁愿意留下，谁想离开，以及你愿意承担哪一种责任。", "Structure, power and navigation connect. The console presents no single correct route. It lists keeping the light, voyaging alone and travelling together, with missing facilities, supplies and replies for each.\n\nYou may prepare more than one route. The list and final supplies are committed only at confirmation. Nobody should be permanently excluded from a future because of a long-ago answer whose consequences were unknown.\n\nChapter four begins. The next task is not blind stockpiling. It is asking who wants to stay, who wants to leave, and which responsibility you will accept.")},
            {"personal-ship",M3Text.Pair("个人航天器的座舱只容得下一个人。你试着坐进去，发现这里没有公共桌，没有第二张椅子，却有朝向未知信号的舷窗。\n\n离开并不使这些日子失去意义。你仍需要交付留守补给，确保家园能源可用，并逐一告诉主要伙伴自己的决定。他们不必祝福，才有资格被告知。", "The personal craft has room for one. Inside there is no shared table, no second chair, but there is a window facing the unknown signals.\n\nLeaving does not erase these days. You still need to deliver ground supplies, leave usable home energy and tell each principal companion what you have decided. They need not offer a blessing to deserve being told.")},
            {"transport",M3Text.Pair("旧运输船的舱门再次打开。地板上有一排没有名字的固定座位。渡没有急着挑选位置，她先问：“这些空位，是邀请，还是已经替别人做好的决定？”\n\n船可以修好，名单仍然可以空着。至少一名机器明确愿意同行，才构成这条道路；拒绝的人不会因为座位空着而被算进去。", "The old transport hatch opens again. A row of fixed seats bears no names. Du does not choose one. 'Are these empty places invitations, or decisions already made for someone else?'\n\nThe ship can be repaired while the list remains empty. At least one machine must explicitly want to travel for this route to be ready. Nobody who refuses is counted simply because a seat is free.")},
            {"collective-power",M3Text.Pair("集体能源工程接入运输船。守标出了乘员容量与留守设施的边界：更多乘员需要更多座位和供给，留在地球的人也不能只得到一句告别。\n\n你核对名单上的答复。这里承载的是愿意离开的这几个人，不是所有地球生命的命运。能承担的承诺，比宏大的宣言更具体。", "Collective power connects to the transport. Shou marks the limits of passenger capacity and ground facilities. More travellers require seats and supplies; those remaining need more than a farewell.\n\nYou check the replies on the list. This ship carries these willing companions, not the fate of every life on Earth. A promise you can keep is more concrete than a grand declaration.")},
            {"supplies",M3Text.Pair("留守补给进入专用储备，交付记录落在控制台上。普通库存仍然可以继续使用，这次交付不会因为反复读档而再扣一遍。\n\n岑把清单折好：“我愿意替你们传话。但我不会承诺每个人都满意，也不会把留在这里说成被剩下。”\n\n这批补给是一次可核对的责任，不要求你站在机器旁边等上几个小时来证明它成立。", "Ground supplies enter the dedicated reserve, and the console records delivery. Ordinary stores remain available. Reloading will not charge for the delivery again.\n\nCen folds the list. 'I will carry messages. I won't promise everyone will be pleased, or describe staying here as being left over.'\n\nThese supplies are a verifiable responsibility. You need not stand beside the machines for hours to prove it.")},
            {"pulse",M3Text.Pair("脉冲发射器装配完成。它消耗随身电芯，给你在危险靠近前作出反应的距离；它不是无限弹药，也不让墙壁失去意义。\n\n工作台已经保留固定配方。电芯可以用普通材料加工，敌人身上的东西不会成为主线唯一来源。", "The pulse launcher is assembled. It consumes carried energy cells and offers distance before danger reaches you. It has neither unlimited ammunition nor the ability to ignore walls.\n\nThe fixed recipe remains at the bench. Cells can be made from ordinary materials. Enemy drops will never become the only way forward.")},
            {"clothing",M3Text.Pair("你把纤维衬层缝进外衣。它减缓冷热暴露，不能代替食物、供暖和夏季散热。\n\n芽摸了摸袖口：“保护不是让天气不存在，是让你有时间回来。”你记下下一季的预报，决定下一次出门前留出一点燃料。", "You stitch a fibre lining into your coat. It slows exposure to heat and cold but cannot replace food, warmth or summer cooling.\n\nYa touches the cuff. 'Protection doesn't remove the weather. It gives you time to come back.' You note the next forecast and decide to leave some fuel before the next trip.")},
            {"ya-request",M3Text.Pair("那盆不开花的植物终于有了自己的位置。芽没有在产出表里给它填写一个虚构的数字。\n\n“我想照顾它。”芽说，“今天没有收获，也可以算作今天的一部分。”\n\n你们约定，岗位可以调整，也可以暂停。请求已经完成，现在可以公开协商共同规则。", "The plant that never flowers finally has a place. Ya does not invent a yield to justify it on the production sheet.\n\n'I want to care for it,' Ya says. 'A day without a harvest can still count as part of a day.'\n\nYou agree that jobs may change or pause. The request is complete; common rules can now be negotiated openly.")},
            {"liang-request",M3Text.Pair("梁用水平仪检查公共桌，确认它并不比工作台更能提高产量。然后它把自己的工具放到桌边，给第二个人留出位置。\n\n“尺寸合格。”它说，停了一会儿又补上，“用途不必只有一种。”\n\n你第一次看见它提出一件没有列在旧任务清单上的东西。接下来，它愿意与你讨论谁可以调整岗位，以及何时可以拒绝。", "Liang checks the shared table with its level and confirms that it improves output no more than a workbench. Then it sets its tools aside, leaving space for another person.\n\n'Dimensions accepted,' it says, then adds: 'There need not be only one purpose.'\n\nFor the first time you see it propose something absent from the old task list. It is ready to discuss who may change a job, and when someone may refuse.")},
            {"shou-request",M3Text.Pair("警戒灯装好之后，守没有把照明范围扩大到每一扇窗。它与你划定了公开边界：预警说明来源和目标，不能把不同意见标记成威胁。\n\n“如果有人不接受命令？”它问。\n\n“先问理由。”\n\n守把这句话记在规则顶部。安全仍然重要，但它不再自动意味着服从。", "Once the watch light is installed, Shou does not extend it to every window. You establish visible limits: warnings state their source and target; disagreement is not labelled a threat.\n\n'If someone rejects an order?' it asks.\n\n'Ask why first.'\n\nShou places that sentence at the top. Safety still matters. It no longer automatically means obedience.")},
            {"du-request",M3Text.Pair("渡接过补给，逐项核对后才把名单放回桌上。她不再只把你叫作“授权者”。\n\n“现在你可以问我想去哪里了。”她说，“不是因为这些东西买下了一个答复，而是因为你先完成了答应过的事。”\n\n你仍然需要邀请她并记录明确回答；补给交付本身不会把她自动加入乘员。", "Du checks each item before returning the list to the table. She no longer calls you only 'the authorizer'.\n\n'Now you can ask where I want to go,' she says. 'Not because these supplies bought an answer, but because you first did what you promised.'\n\nYou must still invite her and record an explicit answer. Delivery alone does not add her to the passengers.")},
            {"cen-repair",M3Text.Pair("你没有要求岑把旧事当作没发生，而是说明当时的处境，把补偿放在桌面上。岑听完，重新画出了那条低风险通道。\n\n“下次没准备好，就直接告诉我。”他说，“我宁愿拿到一个实话，也不想围着一张空床等。”\n\n合作恢复了。旧的选择仍然留在记录里，但它不再是一道无法打开的门。", "You do not ask Cen to pretend the past never happened. You explain your circumstances and place compensation on the table. After listening, he redraws the low-risk passage.\n\n'Next time you aren't ready, say so. I'd rather have an honest answer than wait beside an empty bed.'\n\nCooperation resumes. The old choice remains in the record, but no longer as a door that cannot open.")},
            {"agreement-liang",M3Text.Pair("梁把旧指令中的“持续执行”划掉，改成“在材料、能源与通路允许时执行，可以请求暂停”。它问你要不要再量一次桌面。你们决定先坐一会儿。", "Liang crosses out 'execute continuously' and writes 'execute while materials, energy and access permit; may request a pause'. It asks whether you want the table measured again. You decide to sit for a while first.")},
            {"agreement-ya",M3Text.Pair("芽同意了共同规则，也给那盆植物保留了一个没有产量要求的位置。规则写明照料者可以休息，照料对象不必证明自己有用。", "Ya accepts the common rules and keeps a place for the plant without a yield requirement. The rules say carers may rest, and what they care for need not prove its usefulness.")},
            {"agreement-shou",M3Text.Pair("守确认：警报必须说明缘由，岗位可以协商，拒绝本身不是敌对。它调暗了照向门内的灯，把光留给回家的路。", "Shou confirms: alerts must explain their cause, jobs can be negotiated, and refusal itself is not hostility. It dims the inward-facing lamp and leaves light on the road home.")},
            {"consent",M3Text.Pair("“我愿意同行。”这句话被完整记入名单，包括说话者和答复。空位不再只是技术容量，而是一个已经问过、也可以重新商量的选择。", "'I want to travel with you.' The full reply is recorded with its speaker. A seat is no longer only capacity. It is a choice that was asked about and can still be discussed.")},
            {"refuse",M3Text.Pair("“现在还不愿意。”对方没有被加入乘员名单。你可以完成公开的人物请求，修复共同规则，再来询问。控制台不会把沉默或命令解释成同意。", "'Not yet.' They are not added to the passenger list. You can complete their visible request, repair the common rules and ask again. The console will not interpret silence or an order as consent.")},
            {"stay",M3Text.Pair("留守的答复被记录下来。离开不是成长的唯一形状，留下也不是没有获得席位。你开始核对地面的供给与设施，而不是替对方改写答案。", "The decision to remain is recorded. Departure is not the only form of growth, and staying is not a failure to receive a seat. You check ground supplies and facilities instead of rewriting the answer.")},
            {"informed",M3Text.Pair("你把个人远航的计划讲清楚，包括目的地仍然未知，以及你打算留下什么。对方听完，没有被要求给出祝福。告知已经完成，关系仍然可以有自己的语气。", "You explain your personal voyage, including the uncertain destination and what you will leave behind. The listener is not required to bless it. They have been informed; the relationship retains its own voice.")},
            {"du-consent",M3Text.Pair("渡点头：“这次，名字可以写上去了。”她检查的是自己的答复，而不是船长的命令。你为她预留容量和补给，直到最终确认之前，名单仍然可以调整。", "Du nods. 'This time, you can write my name.' She checks her own reply, not a captain's order. You prepare capacity and supplies; the list remains changeable until final confirmation.")},
            {"du-refuse",M3Text.Pair("渡摇头：“先把答应的事做完。我不想在船上才发现，一个承诺原来只是让人点头的方法。”她的拒绝不会关闭其他路线；完成补给请求后，可以再次邀请。", "Du shakes her head. 'Finish what you promised first. I don't want to discover aboard ship that a promise was only a way of getting a yes.' Her refusal closes no other route. After delivering the supplies, you can invite her again.")},
            {"cen-stay",M3Text.Pair("岑决定留在地球。他愿意做联络者，继续与那些没有出现在这张名单上的人交易、传话。你们的未来不会完全重合，但可以保留一个彼此知道的地址。", "Cen chooses Earth. He will remain a contact, trading and carrying messages for people absent from this list. Your futures need not coincide completely to retain an address known to each other.")},
            {"identity",M3Text.Pair("你说出了现在愿意使用的称呼。制造经历没有因此消失，你曾经感到的冷暖也没有被重新判定。控制台保持相同的工程权限。如何使用它，仍然由之后的行动回答。", "You speak the name you are willing to use now. Your making does not disappear, nor are your experiences of warmth and cold judged anew. Engineering access stays the same. How to use it is still a question for your actions.")},
            {"ending-Light",M3Text.Pair("你把动力从发射倒计时转向地面网络。远处一盏灯亮了，随后是另一盏。它们不是等待命令的标记，而是有人约好可以回来、也可以离开的地方。\n\n梁留下可以坐下的公共桌。芽照料着那盆仍未开花的植物。守报告天气，随后询问今天是否需要继续巡查。岑把新的地址传向远方，渡按照自己的答复安排下一段路。\n\n你放弃了这一次出发，并没有替所有未来作出永久决定。地球不是恢复了旧日秩序，而是多了一份允许拒绝的共同约定。夜里，你没有关掉门外的灯。", "You turn power from the launch countdown toward the ground network. A distant light appears, then another. They are not signs awaiting orders, but places where people agreed they could return, or leave.\n\nLiang keeps the shared table ready. Ya tends the plant that still has not flowered. Shou reports the weather, then asks whether more patrols are wanted today. Cen carries new addresses outward. Du plans her next road according to her own reply.\n\nYou give up this departure, not every possible future. Earth has not recovered its old order; it has gained an agreement that permits refusal. That night, you leave the outside light on.")},
            {"ending-Voyage",M3Text.Pair("个人航天器升起时，家园缩成窗下一小片暖色。留下的补给有清单，伙伴们知道你的决定；他们的生活不会在你离开后停止。\n\n你朝最后的导航信号出发，没有人保证那里仍有人类。你可以承认自己被制造，也可以继续把人类当作自己的名字。这两种说法都不能替你走完前面的路。\n\n梁检查屋子的门，芽收起成熟的作物，守把灯转向地平线。岑会继续传话。你带走了寻找的权利，也接受无法同时守在每一个身边的失去。远航不是背叛的判词，是你选择承担的未知。", "As the personal craft rises, home becomes a small warm patch below the window. The supplies have a ledger, and your companions know your choice. Their lives will not stop when you leave.\n\nYou head for the last navigation signals without a guarantee that humanity remains there. You may acknowledge being made, or keep human as your name. Neither description travels the road for you.\n\nLiang checks the door, Ya gathers mature crops, and Shou turns its light toward the horizon. Cen will keep carrying messages. You take the right to search, accepting that you cannot remain beside everyone. The voyage is no verdict of betrayal. It is uncertainty you choose to bear.")},
            {"ending-Together",M3Text.Pair("运输船里响起不同的准备声。名单上只有明确同意的人，每一个空位也都有被尊重的理由。留守设施仍在运转，岑留在地面接通最后一次联络。\n\n“不要把这说成救走了所有人。”渡曾经这样提醒。你记得。你们带走的是这个小小群体愿意共同承担的未来，不是替地球写下统一的结论。\n\n舱门关闭之前，离开的人向留下的人告别。机器不再只是推动航天器完成任务的工具，而是可以选择目的地的同行者。未知仍然在前方；这一次，有人愿意与你一起面对。", "Different sounds of preparation fill the transport. Only those who explicitly agreed are on the list, and every empty seat has a respected reason. Ground facilities keep working. Cen connects the final call from below.\n\n'Don't call this rescuing everyone,' Du once warned. You remember. You carry the future this small group is willing to bear together, not a single conclusion imposed upon Earth.\n\nBefore the hatch closes, those departing say goodbye to those remaining. Machines are no longer tools completing a spacecraft's task, but companions able to choose a destination. The unknown remains ahead. This time, others have chosen to face it with you.")}
        };
    }
}
