using System;
using System.Linq;
using NUnit.Framework;

namespace LastLight.Tests
{
    public sealed class M1RulesTests
    {
        private static Inventory Stock(){var s=new Inventory(80);foreach(Resource r in Enum.GetValues(typeof(Resource)))Assert.True(s.Add(r,100));return s;}
        [Test] public void StackBoundaryAndTransferAreAtomic(){var a=new Inventory(1);var b=new Inventory(1);Assert.True(a.Add(Resource.Wood,20));Assert.False(a.Add(Resource.Wood,1));Assert.True(b.Add(Resource.Stone,20));Assert.False(a.Transfer(b,Resource.Wood,1));Assert.AreEqual(20,a[Resource.Wood]);Assert.AreEqual(0,b[Resource.Wood]);}
        [Test] public void CraftOutputFullDoesNotConsumeInput(){var s=new Inventory(1);s.Add(Resource.Scrap,20);Assert.False(s.Exchange(Catalog.PartsRecipe,new Cost(Resource.Parts,1)));Assert.AreEqual(20,s[Resource.Scrap]);}
        [Test] public void RepeatedCostsCannotOverdraw(){var s=new Inventory(2);s.Add(Resource.Wood,3);Assert.False(s.Pay(new Cost(Resource.Wood,2),new Cost(Resource.Wood,2)));Assert.AreEqual(3,s[Resource.Wood]);}
        [Test] public void PickupCannotDuplicateAndSurvivesSceneReentry(){var e=new M1EconomySystem();Assert.True(e.Pickup("Home/wood",Resource.Wood,4,180,0));Assert.False(e.Pickup("Home/wood",Resource.Wood,4,180,179));Assert.AreEqual(4,e.Backpack[Resource.Wood]);Assert.True(e.Pickup("Home/wood",Resource.Wood,4,180,180));}
        [Test] public void ReservedLaneCannotBeBuiltOver(){var c=new M1ConstructionSystem();var s=Stock();Assert.IsNull(c.Grid.Place(Structure.Barricade,0,0,0,s,out _));Assert.AreEqual(100,s[Resource.Wood]);}
        [Test] public void DamagedBuildingsCannotMoveOrRefund(){var grid=new BuildGrid();var s=Stock();var b=grid.Place(Structure.Barricade,2,2,0,s,out _);b.health=0;Assert.False(grid.Move(b,3,2,0,out _));Assert.False(grid.Remove(b,s,out _));Assert.AreEqual(97,s[Resource.Wood]);}
        [Test] public void ClosedRoomRequiresDoorAndDestroyedWallOpensIt(){var grid=new BuildGrid();var s=Stock();grid.Place(Structure.Floor,2,2,0,s,out _);for(int i=0;i<3;i++)Assert.NotNull(grid.Place(Structure.Wall,2,2,i,s,out _));Assert.IsNull(grid.Place(Structure.Wall,2,2,3,s,out _));var door=grid.Place(Structure.Door,2,2,3,s,out _);Assert.NotNull(door);Assert.AreEqual(1,grid.Room(2,2,out var hasDoor).Count);Assert.True(hasDoor);door.health=0;Assert.AreEqual(0,grid.Room(2,2,out _).Count);}
        [Test] public void RepairConsumesOnlyAtCompletion(){var c=new M1ConstructionSystem();var s=Stock();var b=c.Grid.Place(Structure.Barricade,2,2,0,s,out _);b.health=0;Assert.True(c.BeginRepair(b,s));Assert.AreEqual(97,s[Resource.Wood]);Assert.False(c.TickRepair(7,s,true,false));Assert.AreEqual(0,b.health);Assert.True(c.TickRepair(1,s,true,false));Assert.AreEqual(100,b.health);Assert.AreEqual(96,s[Resource.Wood]);Assert.False(c.TickRepair(20,s,true,false));}
        [Test] public void BlockedRepairDoesNotAdvanceOrConsume(){var c=new M1ConstructionSystem();var s=Stock();var b=c.Grid.Place(Structure.Barricade,2,2,0,s,out _);b.health=0;c.BeginRepair(b,s);Assert.False(c.TickRepair(40,s,false,true));Assert.AreEqual(0,c.RepairProgress);Assert.AreEqual(97,s[Resource.Wood]);}
        [TestCase(1,2)] [TestCase(2,1)] [TestCase(3,0)]
        public void ChoicesChargeOnceAndNeverRevokeShortcut(int option,int cost){var s=new Inventory(10);var story=new StoryState{liang=true,core=true,shortcut=true};Assert.True(story.ClaimReward(s));Assert.False(story.ClaimReward(s));Assert.True(story.Choose(option,s));Assert.False(story.Choose(option,s));Assert.AreEqual(4-cost,s[Resource.Parts]);Assert.True(story.shortcut);Assert.AreEqual(option==1,story.aidRoute);}
        [Test] public void RefusalWorksWithZeroParts(){var story=new StoryState{liang=true,reward=true};var s=new Inventory(1);Assert.False(story.Choose(1,s));Assert.AreEqual(0,story.choice);Assert.True(story.Choose(3,s));}
        [Test] public void OccupiedBedCannotFulfillPromise(){var story=new StoryState{promise=1};var s=Stock();var bed=new Building(1,Structure.Bed,2,2,0){occupant="player"};Assert.False(story.Fulfill(s,bed));Assert.AreEqual(100,s[Resource.Ration]);Assert.AreEqual(1,story.promise);}
        [Test] public void VisitorBedAndRewardCommitOnce(){var story=new StoryState{promise=1};var s=Stock();var bed=new Building(1,Structure.Bed,2,2,0);Assert.True(story.Fulfill(s,bed));Assert.AreEqual("visitor",bed.occupant);Assert.AreEqual(98,s[Resource.Ration]);Assert.AreEqual(108,s[Resource.Wood]);Assert.False(story.Fulfill(s,bed));}
        [Test] public void FullRewardStorageDoesNotReserveBed(){var story=new StoryState{promise=1};var s=new Inventory(1);s.Add(Resource.Ration,3);var bed=new Building(1,Structure.Bed,2,2,0);Assert.False(story.Fulfill(s,bed));Assert.AreEqual("",bed.occupant);Assert.AreEqual(3,s[Resource.Ration]);}
        [Test] public void PromiseHasOneExtensionAndExplicitWithdrawal(){var story=new StoryState{promise=1};Assert.True(story.ExtendPromise());Assert.False(story.ExtendPromise());Assert.True(story.WithdrawPromise());Assert.False(story.WithdrawPromise());}
        [Test] public void RescueDoesNotTouchStorageOrStory(){var e=new M1EconomySystem();var v=new M1SurvivalSystem();var story=new StoryState{core=true,liang=true};e.Backpack.Add(Resource.Wood,19);e.Storage.Add(Resource.Wood,20);v.Damage(100);v.Rescue(e.Backpack);Assert.AreEqual(16,e.Backpack[Resource.Wood]);Assert.AreEqual(20,e.Storage[Resource.Wood]);Assert.True(story.core);Assert.Greater(v.Health,0);}
        [Test] public void RaidLossHasCapAndSingleSettlement(){var t=new M1ThreatSystem();var story=new StoryState{choice=3,defenseRead=true};var s=Stock();Assert.True(t.Start(0,story,true));Assert.True(t.RecordEquipment(1));Assert.True(t.RecordEquipment(2));Assert.False(t.RecordEquipment(3));Assert.True(t.Finish(true,100,story,s));Assert.False(t.Finish(true,101,story,s));Assert.AreEqual(95,s[Resource.Wood]);Assert.AreEqual(1900,t.BufferUntil);}
        [Test] public void ZeroInventoryCanRecoverWithoutMachineOrBench(){var e=new M1EconomySystem();foreach(var r in new[]{Resource.Wood,Resource.Stone,Resource.Fiber,Resource.Ration,Resource.Scrap})Assert.True(e.Pickup("safe/"+r,r,4,180,0));e.Backpack.Deposit(e.Storage);Assert.True(e.CraftFuel());Assert.True(e.CraftParts());Assert.AreEqual(1,e.Storage[Resource.Fuel]);Assert.AreEqual(1,e.Storage[Resource.Parts]);}
        [Test] public void AllOrdinaryRecipesHaveRenewableSources(){foreach(Structure kind in Enum.GetValues(typeof(Structure)))foreach(var cost in Catalog.Recipe(kind))Assert.Contains(cost.resource,new[]{Resource.Wood,Resource.Stone,Resource.Fiber,Resource.Scrap});}
    }
}
